server:
  port: 8888

spring:
  cloud:
    config:
      name: configserver
      server:
        git:
          uri: ${__CONFIG_REPO:file:///C:/Users/kjayapal/git/config-data}
               