server:
  port: 8888

spring:
  cloud:
    config:
      name: configserver
      server:
        git:
          uri: ${__CONFIG_REPO:https://github.com/kjayapal/config-data}
               